### ISSUE TITLE
db.collection('name').find().toArray(function(err, results){}) don't work in os x 10.8/9

### ISSUE THREAD

**Issue by zhaoyou** [kissjs/node-mongoskin#125]
```
 var mongo = require('mongoskin');

 exports.test = function(req, res) {
   var db = mongo.db('localhost:27017/btc', {safe: false});
   db.collection('user').find({}).toArray(function(err, results){
     console.log(results)
     res.json(200, {'flag': true});
  });
}
```

why this code work well in linux (ubuntu12.04). don't work in os x 10.8/9 (node version, mongoskin version is the some)

error message: 

```
  /Users/apple/code/btcwallet_api/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/connection/base.js:242
    throw message;      
          ^
 TypeError: undefined is not a function
at commandHandler   /Users/apple/code/btcwallet_api/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/cursor.js:706:16)
at /Users/apple/code/btcwallet_api/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/db.js:1801:9
at Server.Base._callHandler (/Users/apple/code/btcwallet_api/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
at /Users/apple/code/btcwallet_api/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
at MongoReply.parseBody (/Users/apple/code/btcwallet_api/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
at null.<anonymous> (/Users/apple/code/btcwallet_api/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
at EventEmitter.emit (events.js:95:17)
at null.<anonymous> (/Users/apple/code/btcwallet_api/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
at EventEmitter.emit (events.js:98:17)
at Socket.<anonymous> (/Users/apple/code/btcwallet_api/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/connection/connection.js:418:22)
```
