### ISSUE TITLE
Got an error in 1.4.11 - "Cannot read property 'name' of undefined"

### ISSUE THREAD

**Issue by zag2art** [kissjs/node-mongoskin#153]
```bash
/home/zag2art/work/idg/node_modules/local-derby-server/node_modules/livedb-mongo/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^
TypeError: Cannot read property 'name' of undefined
  at makeSkinClass (/home/zag2art/work/idg/node_modules/local-derby-server/node_modules/livedb-mongo/node_modules/mongoskin/lib/utils.js:33:43)
  at Object.<anonymous> (/home/zag2art/work/idg/node_modules/local-derby-server/node_modules/livedb-mongo/node_modules/mongoskin/lib/admin.js:18:37)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/zag2art/work/idg/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/zag2art/work/idg/node_modules/local-derby-server/node_modules/livedb-mongo/node_modules/mongoskin/lib/db.js:20:17)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/zag2art/work/idg/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/zag2art/work/idg/node_modules/local-derby-server/node_modules/livedb-mongo/node_modules/mongoskin/lib/mongo_client.js:5:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/zag2art/work/idg/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /home/zag2art/work/idg/node_modules/local-derby-server/node_modules/livedb-mongo/node_modules/mongoskin/lib/index.js:25:15
  at Array.forEach (native)
  at Object.<anonymous> (/home/zag2art/work/idg/node_modules/local-derby-server/node_modules/livedb-mongo/node_modules/mongoskin/lib/index.js:24:80)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/zag2art/work/idg/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/zag2art/work/idg/node_modules/local-derby-server/node_modules/livedb-mongo/node_modules/mongoskin/index.js:1:132)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/zag2art/work/idg/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/zag2art/work/idg/node_modules/local-derby-server/node_modules/livedb-mongo/mongo.js:2:17)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/zag2art/work/idg/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/zag2art/work/idg/node_modules/local-derby-server/server/store.js:10:17)
  at Object.<anonymous> (/home/zag2art/work/idg/node_modules/local-derby-server/server/store.js:114:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/zag2art/work/idg/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at module.exports (/home/zag2art/work/idg/node_modules/local-derby-server/server/index.js:61:13)
  at Object.derbyServer.run (/home/zag2art/work/idg/node_modules/local-derby-server/index.js:64:33)
  at module.exports (/home/zag2art/work/idg/src/server/index.coffee:19:22)
  at Object.<anonymous> (/home/zag2art/work/idg/server.js:13:26)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3
```

**Comment by paulhill** [comment]
+1
Transitive dependency from agenda. Preventing our builds.

**Comment by tj** [comment]
still getting this as well

**Comment by vkarpov15** [comment]
Can you clarify what version of the mongodb npm module you're using?

**Comment by tj** [comment]
we're using whatever `monk` pulls in: `"mongoskin": "1.4.11"`

**Comment by treywashington** [comment]
Having the same issue through monk.

**Comment by konstantine33** [comment]
I am having the same issue as well

**Comment by kimeshan** [comment]
Same issue here!

**Comment by Sqone** [comment]
+1 Same issue here width monk : 
if it could help, 

"dependencies": {
    "mongoskin": "1.4.11",
    "debug": "*",
    "mpromise": "0.5.1"
  },

**Comment by kimeshan** [comment]
@Sqone I got monk to work by changing the dependency to version "mongoskin": "1.3.20". Monk by default will install 1.4.11 which seems to be broken. The previous version of mongoskin (1.3.20) seems to be fine.

**Comment by iposton** [comment]
@kimeshan can you clarify which dependencies you changed or better yet post your dependencies in the comments. Thank you!

**Comment by kimeshan** [comment]
@iposton I changed the mongoskin version in my monk dependencies:

This is in my package.json inside node_modules/monk:
  "dependencies": {
    "debug": "*",
    "mongoskin": "^1.3.20",
    "mpromise": "0.5.1"
  }

This gets Monk to work. Monk requires Mongoskin and it seems that the latest push of Mongoskin is broken due to the NativeClass error here. So changing to 1.3.20 will tell npm to pull the previous working version of Mongoskin, which Monk can work with.

Hope that helps.

**Comment by iposton** [comment]
@kimeshan I see. I changed the mongoskin to ^1.3.20 then did npm install but still getting same error.  Is there a command to get npm to see the new change in monk?

**Comment by kimeshan** [comment]
@iposton I was having some problems with that too. I did the unbuild and then install, and that worked. Changing the package.json and then doing npm install didn't play nice when I tried it.

So unbuild mongoskin when you're inside node_modules/monk, then install by specifying the version with @. 

npm unbuild mongoskin --save
npm install mongoskin@1.3.20 --save

**Comment by kimeshan** [comment]
@iposton I was having some problems with that too. I did the uninstall and then install, and that worked. Changing the package.json and then doing npm install didn't play nice when I tried it.

So uninstall mongoskin when you're inside node_modules/monk, then install by specifying the version with @.

npm uninstall mongoskin --save
npm install mongoskin@1.3.20 --save

**Comment by iposton** [comment]
Yes! This solved my issue! Great work @kimeshan 

no more error and the Server is now running on port 3000

**Comment by ar2rsawseen** [comment]
The issue is because mongoskin installs newest mongodb driver

```
"peerDependencies": {
    "mongodb": ">= 1.4"
  },
```

And the newest released mongodb drive is `"version": "2.0.24"`
which is not compatible with mongoskin anymore

So limiting dependency to 

```
"peerDependencies": {
    "mongodb": "1.4.x"
  },
```

should fix the issue for now

**Comment by vkarpov15** [comment]
1.4.13 uses `"mongodb": "~1.4"`, see #159

**Comment by javlc** [comment]
Got this error as well, did research and now I have a new, different error:
More details in the following gist:
https://gist.github.com/javlc/67220256c6e51573dc07

**Comment by vkarpov15** [comment]
@javlc not related to this issue. Also, mongoskin should work just fine even if the C++ bson build failed.

**Comment by statelo** [comment]
@kimeshan Thank you so much! Installing mongoskin version 1.3.20 helped me to solve this problem!!

**Comment by vikramparihar** [comment]
@kimeshan Thank you so much! Installing mongoskin version 1.3.20 helped me to solve this problem!!

**Comment by enn-code** [comment]
Downgrading is not really a great long term solution though. I'm new to Monk, is it outdated?

**Comment by statelo** [comment]
@jaegerbombb yeah kind of like this...don`t forget that mongoskin version works with mongodb of version 1.4.x! that also helped me.

**Comment by ghost** [comment]
@sylvainkossi
Thank you  @iposton. I get the issue fixed now.

**Comment by asemoon** [comment]
What's the status of this issue? has it been fixed to work with latest version of mongo?

**Comment by Aparaxium** [comment]
I seem to be getting this error still.

**Comment by ivansf** [comment]
Getting the same issue. @kimeshan solution worked for me.

**Comment by statelo** [comment]
Actually I don`t know does this method works...I just leaved this warning...The one thing which I did, the latest version of mongoskin is 1.0.1, so what you need it is just download mongodb of version 1.4.x because mongoskin version 1.0.1 only compatible with this mongodb version

**Comment by Aggie123** [comment]
1.4.13 uses "mongodb": "~1.4", see #159 works, 
but still encounter further error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' } js-bson: Failed to load c++ bson extension, using pure JS version
Find a [solution](https://stackoverflow.com/questions/28651028/cannot-find-module-build-release-bson-code-module-not-found-js-bson/28932441#28932441) to this FYI in case anyone need:

**Comment by memosngular** [comment]
I solved my issue with @kimeshan solution
